example = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

with open('input.txt') as f:
    # puzzle_input = example
    puzzle_input = f.read().strip()
    first, *rest = puzzle_input.split('\n')
    index = first.index('S')
    width = len(first)

    active = [False] * width
    active[index] = True
    splits = 0
    for line in rest:
        for i, _ in enumerate(active):
            if line[i] == '^' and active[i]:
                active[i] = False
                splits += 1
                if i > 0:
                    active[i - 1] = True
                if i < width - 1:
                    active[i + 1] = True

print(splits)

