example = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

with open('input.txt') as f:
    # puzzle_input = example
    puzzle_input = f.read().strip()
    first, *rest = puzzle_input.split('\n')
    index = first.index('S')
    width = len(first)

    active = [0] * width
    active[index] = 1
    for line in rest:
        temp = [0] * width
        for i, _ in enumerate(active):
            if line[i] == '^' and active[i]:
                if i > 0:
                    temp[i - 1] += active[i]
                if i < width - 1:
                    temp[i + 1] += active[i]
            else:
                temp[i] += active[i]
        active = temp

print(sum(active))

